# Netlify configuration file

[build]
  # Directory to publish (static site)
  publish = "dist"
  # Use our dedicated Netlify build script
  command = "bash ./scripts/netlify-build.sh"
  # Directory with serverless functions
  functions = "netlify/functions"

# API requests to be handled by Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set environment variables (for development purposes)
# For actual sensitive values, set these in the Netlify UI
[build.environment]
  NODE_ENV = "production"